require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

project 'nativeBase',
  'Debug-dev' => :debug,
  'Release-dev' => :release,
  'Debug' => :debug,
  'Release' => :release

target 'nativeBase' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'nativeBaseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.95.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

def add_flipper_pods!
  version = '~> 0.35.0'
  pod 'FlipperKit', version, :configuration => ['Debug-dev', 'Release-dev']
  pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => ['Debug-dev', 'Release-dev']
  pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => ['Debug-dev', 'Release-dev']
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => ['Debug-dev', 'Release-dev']
  pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => ['Debug-dev', 'Release-dev']
end

target 'nativeBase-tvOS' do
  # Pods for nativeBase-tvOS

  target 'nativeBase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end